version: '2'
services:
  omar-avro-app:
    # networks:
    #   - docker_default
    image: omar-avro-app:latest
    volumes:
      - /dev/urandom:/dev/random
      # - /home:/home
      # - /Users:/Users
    environment:
      SPRING_CLOUD_CONFIG_ENABLED: "false"
      SPRING_CLOUD_DISCOVERY_ENABLED: "false"
    ports:
      - "8080:8080"
networks:
  default:
    external:
      name: docker_default
